config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "recipes#my_recipes"

  get '/public-recipes', to: 'recipes#public_recipes'
  get '/recipes', to: 'recipes#my_recipes'
  get '/foods', to: 'foods#my_foods'
  get '/recipes/:id/shopping_list', to: 'recipes#shopping_list', as: 'recipe_shopping_list'
  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'recipe_toggle_public'

  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy]
  end
  resources :foods, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, :measurement_unit, :price, :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :set_current_user

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  private

  def set_current_user
    @current_user = current_user
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params.merge(user: current_user))
    respond_to do |f|
      if @food.save
        f.html { redirect_to foods_path, notice: 'Food added' }
      else
        f.html { render :new, notice: 'Failed to add food' }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id]).destroy
    respond_to do |f|
      f.html { redirect_to foods_path, notice: 'Food deleted' }
    end
  end

  def my_foods
    @foods = current_user.foods.includes(:user)
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[destroy]
  before_action :set_recipe, only: %i[new create]

  def new
    @recipe_food = @recipe.recipe_foods.build
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params.merge(recipe: @recipe))

    if @recipe_food.save
      redirect_to @recipe, notice: 'Recipe ingredient added'
    else
      render :new
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to @recipe_food.recipe, notice: 'Recipe ingredient removed'
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |f|
      if @recipe.save
        f.html { redirect_to recipes_path, notice: 'Recipe created' }
      else
        f.html { render :new }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    respond_to do |f|
      f.html { redirect_to recipes_path, notice: 'Recipe removed' }
    end
  end

  def my_recipes
    @recipes = current_user.recipes.includes(:user)
  end

  def public_recipes
    @recipes = Recipe.includes(:user).where(public: true).order(created_at: :desc)

    @shopping_lists = {}
    @recipes.each do |recipe|
      @shopping_lists[recipe.id] = generate_shopping_list(recipe)
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe
  end

  def shopping_list
    @recipe = Recipe.find(params[:id])
    @shopping_list = generate_shopping_list(@recipe)
  end

  def generate_shopping_list(recipe)
    recipe_foods = RecipeFood.where(recipe:)

    shopping_list = {}

    recipe_foods.each do |recipe_food|
      food = Food.find(recipe_food.food_id)
      quantity = recipe_food.quantity
      measurement_unit = food.measurement_unit

      if shopping_list[food.name].nil?
        shopping_list[food.name] =
          { quantity:, measurement_unit:, price: food.price, name: food.name }
      else
        shopping_list[food.name][:quantity] += quantity
        shopping_list[food.name][:price] += food.price
      end
    end

    shopping_list
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/my_foods.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="d-flex justify-content-end">
        <%= link_to "Add Food", new_food_path, class: "btn btn-primary my-3" %>
      </div>
      <table class="table table-dark table-striped table-bordered table-hover align-middle">
        <thead>
          <tr>
            <th>Name</th>
            <th>Measurement Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td><%= number_to_currency(food.price) %></td>
              <td><%= food.quantity.ceil %></td>
              <td><%= link_to "DELETE", food,
                data: { turbo_method: :delete, turbo_confirm: 'Delete this food?' },
                class: "link-danger text-decoration-none" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h2 class="display-6 text-center">Add Food</h2>
      <%= form_with model: @food, url: foods_path, local: true, html: { class: "row g-3 my-3" } do |form| %>
        <div class="col-12">
          <%= form.text_field :name, class: "form-control", placeholder: "Food name", required: true %>
        </div>

        <div class="col-lg-6">
          <%= form.number_field :price, class: "form-control", placeholder: "Price ($)", required: true %>
        </div>

        <div class="col-lg-6">
          <%= form.number_field :quantity, class: "form-control", placeholder: "Quantity", required: true %>
        </div>

        <div class="col-12">
          <%= form.label :measurement_unit, class: "form-label" %>
          <%= form.select :measurement_unit, options_for_select(['pcs', 'lbs', 'kgs'], selected: 'pcs'), class: "form-select", required: true %>
        </div>

        <div class="col-12">
          <%= form.submit "Add Food", class: "btn btn-primary", style: "width: 100%" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-white text-center py-3 mt-auto">
  <div class="container">
    <p class="m-0">&copy; 2023 Recipe App. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand text-uppercase" href="/">Recipe App</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="navbar-nav ms-auto">
          <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link" %>
          <%= link_to 'My Foods', foods_path, class: "nav-link" %>
          <%= link_to 'My Recipes', recipes_path, class: "nav-link" %>
        </div>

        <span class="mx-2">|</span>

        <div class="d-flex justify-content-center align-items-center gap-3">
          <% if user_signed_in? %>
            <p class="navbar-text ps-2 m-0">
              Signed in as <strong><%= current_user.name %></strong>
            </p>
            <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
          <% else %>
            <div class="ps-2 d-flex gap-2">
              <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-sm btn-info' %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-sm btn-outline-info' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-dark text-light">
    <%= render 'layouts/header' %>

    <% if notice.present? %>
      <div class="alert alert-info m-3" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning m-3" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h1 class="display-6 text-center mb-5">Add ingredient for recipe</h1>

      <%= form_for [@recipe, @recipe_food], html: { class: 'col-lg-8 mx-auto' } do |f| %>
        <div class="mb-3">
          <%= f.label :food_id, "Ingredient" %>
          <%= f.collection_select :food_id, Food.all, :id, :name, prompt: "Select ingredient", class: "form-select" %>
        </div>

        <div class="mb-3">
          <%= f.number_field :quantity, placeholder: "Quantity", class: "form-control" %>
        </div>

        <%= f.submit "Add ingredient to recipe", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_recipe_foods.html.erb
<table class="table table-dark table-striped table-bordered table-hover align-middle">
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.food.quantity.ceil %></td>
        <td><%= number_to_currency(recipe_food.food.price) %></td>
        <td>
          <%= link_to "REMOVE", recipe_recipe_food_path(@recipe, recipe_food),
            data: { turbo_method: :delete, turbo_confirm: 'Delete this ingredient?' },
            class: "link-danger text-decoration-none"
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recipes/my_recipes.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="d-flex justify-content-end">
        <%= link_to "Add Recipe", new_recipe_path, class: "btn btn-primary my-3" %>
      </div>
      <% @recipes.each do |recipe| %>
        <div class="card border-secondary bg-dark mb-3">
          <div class="card-body d-flex justify-content-between align-items-center">
            <div>
              <h3 class="card-title">
                <%= link_to recipe.name, recipe_path(recipe.id), class: "text-decoration-none text-light fw-bold" %>
              </h3>
              <%= link_to "REMOVE", recipe,
                data: { turbo_method: :delete, turbo_confirm: 'Delete this recipe?' },
                class: "link-danger text-decoration-none"
              %>
            </div>
            <p class="card-text"><%= recipe.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h2 class="display-6 text-center">New Recipe</h2>

      <%= form_with model: @recipe, url: recipes_path, local: true, html: { class: "row g-3" } do |form| %>
        <div class="col-12">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="col-lg-6">
          <%= form.label :preparation_time, "Preparation time (min.)", class: "form-label" %>
          <%= form.number_field :preparation_time, min: 0, class: "form-control", required: true %>
        </div>

        <div class="col-lg-6">
          <%= form.label :cooking_time, "Cooking time (min.)", class: "form-label" %>
          <%= form.number_field :cooking_time, min: 0, class: "form-control", required: true %>
        </div>

        <div class="col-12">
          <%= form.label :description, "Steps go here:", class: "form-label" %>
          <%= form.text_area :description, class: "form-control", required: true %>
        </div>

        <div class="col-12">
          <%= form.label :public, class: "form-check-label" %>
          <%= form.check_box :public, class: "form-check-input" %>
        </div>

        <div class="col-12">
          <%= form.submit "Create Recipe", class: "btn btn-primary", style: "width: 100%" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <% @recipes.each do |recipe| %>
      <% shopping_list, _, total_price = @shopping_lists[recipe.id] %>
        <div class="card border-secondary d-flex flex-row justify-content-between bg-dark p-3 mb-3">
          <div>
            <h3 class="card-title">
              <%= link_to recipe.name, recipe_path(recipe.id), class: "text-decoration-none text-light fw-bold" %>
            </h3>
            <p class="card-text">By: <%= recipe.user.name %></p>
          </div>
          <div>
            <p class="card-text">Total items: <%= shopping_list.size %></p>
            <p class="card-text">Total price: <%= number_to_currency(total_price) %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/shopping_list.html.erb
<div class ="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h1 class="display-6 text-center mb-5">Shopping List</h1>
      <div class="d-flex justify-content-evenly">
          <p class="fw-bold">Amount of food items to buy: <%= @shopping_list.size %></p>
          <% total_price = 0 %>
          <% @shopping_list.each do |food, details| %>
            <% total_price += details[:quantity] * details[:price] %>
          <% end %>
          <p class="fw-bold">Total value of food needed: <%= number_to_currency(total_price) %></p>
      </div>

      <table class="table table-dark table-striped table-bordered table-hover align-middle">
        <thead>
          <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% @shopping_list.each do |food, details| %>
            <tr>
              <td><%= food %></td>
              <td><%= details[:quantity] %></td>
              <td><%= number_to_currency(details[:price] * details[:quantity]) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="row">
        <h1 class="text-center mb-5"><%=@recipe.name%></h1>
        <div class="d-flex justify-content-between">
          <h4 class="mb-3">Preparation time: <%= @recipe.preparation_time.ceil %> minutes</h4>

          <% if user_signed_in? && current_user == @recipe.user %>
          <div class="form-check form-switch">
            <div class="form-check">
              <%= label_tag "public", "Public", class: "form-check-label" %>
              <%= form_tag recipe_toggle_public_path(@recipe), method: :put, class: 'd-inline' do %>
                <%= hidden_field_tag :public, 0 %>
                <%= check_box_tag "public", "1", @recipe.public, class: "form-check-input",
                  data: { "role": "switch" }, onChange: "this.form.submit();" %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <h4 class="mb-3">Cooking time: <%= @recipe.cooking_time.ceil %> minutes</h4>
      <p class="mb-3">Description: <%= @recipe.description %></p>

      <div class="d-grid gap-2 d-flex justify-content-center my-4">
        <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe), class: "btn btn-primary" %>
        <%= link_to "Create Shopping List", recipe_shopping_list_path(@recipe), class: "btn btn-info" %>
      </div>

      <%= render partial: "recipe_foods", locals: { recipe: @recipe } %>
    </div>
  </div>
</div>